#!/bin/bash
DEVICE_IP="192.168.0.98"
PACKAGE_NAME="com.sadjockerking.robolve"
robolve_root=$(xdg-user-dir DOCUMENTS)

sh Extras/copyfiles.sh
cd $robolve_root/projects/Robolve/

# Chech if there are devices connected, if not connect to the default ip, if not exit
adb devices | grep "device$" ||
adb connect $DEVICE_IP | grep "connected" ||
{ echo "There is no device to run the app"; exit; }

# Turn on screen for feedback purposes
adb shell dumpsys power | grep 'mHoldingDisplaySuspendBlocker=false' &&
adb shell input keyevent 26 &&
adb shell input keyevent 82

# Compile and run project
cocos run -p android && echo "Success"
[ $? -ne 0 ] && echo "Failure" && exit

# Try to turn it on again just in case
adb shell dumpsys power | grep 'mHoldingDisplaySuspendBlocker=false' &&
adb shell input keyevent 26 &&
adb shell input keyevent 82

# Use pidcat (an improved logcat) for showing debug messages from this project
pidcat $PACKAGE_NAME
